version: '3'
services:
  backend:
    network_mode: "bridge"
    container_name: wagtail_vue_backend
    image: wagtail_vue_backend_image
    ports:
      - "8000:8000"
    volumes:
      - ${WINDIR}.:/app
    stdin_open: true
    command: /opt/entry.sh
